apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: python:3.9
          command: ["python", "-m", "http.server", "8080"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: react-files
              mountPath: /usr/share/react
          resources:
            requests:  # Minimum guaranteed resources
              cpu: "100m"   # 0.1 CPU core
              memory: "128Mi"  # 128 MB RAM
            limits:  # Maximum resources allowed
              cpu: "500m"   # 0.5 CPU core
              memory: "256Mi"  # 256 MB RAM
      volumes:
        - name: react-files
          configMap:
            name: react-configmap
